name: Change P0 label to P1 after 60 days

on:
  schedule:
    - cron: '*/5 * * * *'
  issues:
    types: [opened]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "P1"
          remove-labels: "P0"
