on:
  issues:
    types: 
     - opened
     - reopened

jobs:
  check_label:
    runs-on: ubuntu-latest
    outputs:
      days: ${{ steps.set_label_date.outputs.days }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set label date
      id: set_label_date
      run: |
        label=$(jq -r ".label.name" $GITHUB_EVENT_PATH)
        echo "::set-output name=date::$(jq -r '.label.created_at' $GITHUB_EVENT_PATH)"
        echo "::set-output name=label::${label}"
    - name: Check label age
      id: check_label
      run: |
        days=$(( ($(date -u +%s) - $(date -u -d ${{ steps.set_label_date.outputs.date }} +%s)) / 86400 ))
        if [ $days -gt 60 ]; then
          echo "::set-output name=days::${days}"
        else
          echo "::set-output name=days::0"
        fi

  update_label:
    runs-on: ubuntu-latest
    needs: check_label
    if: ${{ needs.check_label.outputs.days }} != '0' && needs.check_label.outputs.label == 'P0'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Update label
      uses: peter-evans/labeler@v2.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        labels: P1
        add-remove: remove
        old-labels: P0
