name: Change P0 label to P1 after 60 days

on:
  schedule:
    - cron: '*/5 * * * *'
  issues:
    types: [opened]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: remove label
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: P0
          type: remove
      - name: Add label
        uses: buildsville/add-remove-label@v2.0.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: P1
          type: add
          
