name: Label changer

on:
  schedule:
    - cron: '*/5 * * * *'
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
     - uses: actions/github-script@v6
       with:
         script: |
           github.rest.issues.addLabel({
           issue_number: context.issue.number,
           owner: context.repo.owner,
           repo: context.repo.repo,
           labels: ["P1"]
           })
     - uses: actions/checkout@v2
     - uses: actions-ecosystem/action-remove-labels@v1
       with:
         labels: P0
