name: Update priority label

on:
  schedule:
    - cron: '*/5 * * * *'  # runs every day at midnight

jobs:
  update_priority_label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update priority label
      uses: peter-evans/wait-action@v2
      with:
        time: 60d

    - name: Check P0 issues
      id: find_issues
      uses: peter-evans/find-issues@v1
      with:
        query: 'is:open label:P0'

    - name: Change label
      if: steps.find_issues.outputs.total_count > 0
      uses: peter-evans/update-issue-label@v1
      with:
        label: 'P1'
        add: false
        remove: true
        issue-number: ${{ steps.find_issues.outputs.issues[0].number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
