name: Update priority label

on:
  schedule:
    - cron: '*/2 * * * *' # Run every day at midnight

jobs:
  change_priority_label:
    runs-on: ubuntu-latest
    steps:
      - name: Get P0-labeled issues older than 60 days
        id: get_issues
        uses: peter-evans/find-comment@v1
        with:
          issue-type: issue
          issue-query: 'is:open label:P0'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Priority Label
        uses: actions/github-script@v4
        with:
          script: |
            const issues = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: 'P0'
            });
            for (const issue of issues.data) {
              const issue_number = issue.number;
              const created_at = issue.created_at;
              const days = Math.round((Date.now() - new Date(created_at)) / (1000 * 60 * 60 * 24));
              if (days >= 60) {
                await github.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue_number,
                  name: 'P0'
                });
                await github.issues.addLabels({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: issue_number,
                  labels: ['P1']
                });
              }
            }
          
