name: Update Label
on:
  schedule:
    - cron: '*/5 * * * *' # Runs every day at 12:00 AM UTC
  issues:
    types: [opened, edited, labeled]
jobs:
  update-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Label
        uses: peter-evans/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: P1
          added-labels: P1
          removed-labels: P0
          issue-labels: P0
          days-before: 60
