name: Change P0 label to P1 after 60 days

on:
  schedule:
    - cron: '*/5 * * * *'
  issues:
    types: [opened]

jobs:
  add-label:
    name: Add Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: christianvuerings/add-labels@v1
        with:
          labels: |
            P1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
