name: Check Issue Priority

on:
  schedule:
    - cron: '*/5 * * * *’

jobs:
  check-issue-priority:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check issue priority
      run: |
        token=$GITHUB_TOKEN
        user=USERNAME
        repo=REPO_NAME
        label_p0="P0"
        label_p1="P1"
        days=60
        date=$(date -u +"%Y-%m-%dT%H:%M:%SZ" -d "-$days days")
        query="repo:$user/$repo is:issue is:open label:$label_p0 updated:<$date"
        issues=$(curl -s -H "Authorization: token $token" "https://api.github.com/search/issues?q=$query" | jq -r '.items[].number')
        for issue in $issues
        do
          labels=$(curl -s -H "Authorization: token $token" "https://api.github.com/repos/$user/$repo/issues/$issue/labels" | jq -r '.[].name')
          if [[ $labels == *"$label_p0"* ]]; then
            curl -s -X PATCH -H "Authorization: token $token" -H "Content-Type: application/json" -d "{\"labels\":[\"$label_p1\"]}" "https://api.github.com/repos/$user/$repo/issues/$issue"
            echo "Priority of issue #$issue updated from P0 to P1"
          fi
        done
